name: lauraiz
favicon: null
layout_spectrum: 0.5040536194574088
typography_spectrum: 0.5484796832315624
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4639209108427167
  lightness: 0.23451275890693069
  saturation: 0.3731479858979583
  rhythmicContrast: 0.4238821149338037
purpose: []
